apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: pingpong.com
    http:
      paths:
      - path: /api/v1/
        pathType: Prefix
        backend:
          service:
            name: player-service
            port:
              number: 8888