apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-deployment
  labels:
    app: player
spec:
  replicas: 3
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      name: player-pods
      labels:
        app: player
    spec:
      containers:
        - name: player
          image: prapatkiingz/boilerplate-pingpong-player:latest
          ports:
          - containerPort: 8888
          envFrom:
          - configMapRef:
              name: player-config
          - secretRef:
              name: player-secret
         
---
kind: Service
apiVersion: v1
metadata:
  name:  player-service
spec:
  selector:
    app:  player
  type: ClusterIP
  ports:
  - port:  8888
    targetPort:  8888