apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-deployment
  labels:
    app: player
spec:
  replicas: 3
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      name: player-pods
      labels:
        app: player
    spec:
      containers:
        - name: player
          image: prapatkiingz/boilerplate-pingpong-player:latest
          ports:
          - containerPort: 8888
          env:
          - name: MYSQL_HOST
            value: "mariadb:3306"
          - name: TABLE_URL
            value: "http://table-service:8889"
          - name: REDIS_HOST
            value: "pingpong-redis-master:6379"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_USERNAME
            value: "example"
          - name: MYSQL_DATABASE
            value: "pingpong"
---
kind: Service
apiVersion: v1
metadata:
  name:  player-service
spec:
  selector:
    app:  player
  type: ClusterIP
  ports:
  - port:  8888
    targetPort:  8888